// Generated by https://quicktype.io
import { ReactElement } from "react";

export interface IconosInterface {
  expedientes: Expedientes;
}

export interface Expedientes {
  id: number;
  name: string;
  icon: ReactElement;
  enum: string;
}
